### ISSUE TITLE
Cannot reproduce your cool results

### ISSUE THREAD

**Issue by hadaev8** [ConorLazarou/AEGAN-keras#2]
I can see 2 reasons
1 (more likely) I did something wrong.
2 your model overfitted.

Would you like to train on a bigger dataset to check the second case?
https://drive.google.com/file/d/1AUN8ySF18SAKCu1K5-kWUXDQfBr-u9Oy/view?usp=sharing

**Comment by hadaev8** [comment]
This is how my outputs looks like.
https://i.imgur.com/5V0AnUE.png
684 156 train steps

**Comment by RileyLazarou** [comment]
Have you made any modifications to the code?

**Comment by hadaev8** [comment]
Yes, I'm doing aegan in PyTorch.
This is not a "true" reproduce approach, I'm trying to use the idea in general.
I combined some other ideas in a single project, so the most likely problem on my side.
But want to be sure my problems not because of dataset.
If you have time to run it.

**Comment by RileyLazarou** [comment]
Unfortunately my GPU is all tied up on another project for the foreseeable future

**Comment by hadaev8** [comment]
Did you tried google colab?

**Comment by RileyLazarou** [comment]
Thanks for your enthusiasm, if you're interested in comparing your code to this public repo then I'd suggest cloning it and running a side-by-side comparison

**Comment by hadaev8** [comment]
Thanks for response.
